# Site

name: "Mark's Maker Space"
title: "Mark's Maker Space"
description: "3D Printing, 3D Modeling, Coding, Woodworking and generally making stuff"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marksmakerspace.com" # the base hostname & protocol for your site, e.g. http://example.com

google_tag_manager: GTM-W9MRP88
google_analytics: UA-4098886-2
# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

permalink: /:categories/:title:output_ext

# Authors
authors:
  mark:
    name: "Mark Carroll"
    display_name: Mark
    avatar: "/assets/images/avatar.jpeg"
    email: mark@marksmakerspace.com
    web: https://www.marksmakerspace.com
    twitter: marksmakerspace
    instagram: marksmakerspace
    description: "Making stuff with technology...<br>
    Code, 3D Printing, Woodworking"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"
livereload: true
include: ["_pages"]
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
